/**
 * Editor command action types (domain SSOT; app layer CANVAS_ACTIONS aligned with these).
 */
export const EDITOR_ACTIONS = Object.freeze({
    SET_TOOL_MODE: "SET_TOOL_MODE",
    SET_NODE_MODE: "SET_NODE_MODE",
    COPY_SELECTED_OBJECTS: "COPY_SELECTED_OBJECTS",
    PASTE_COPIED_OBJECTS: "PASTE_COPIED_OBJECTS",
    DUPLICATE_SELECTED_OBJECTS: "DUPLICATE_SELECTED_OBJECTS",
    SET_TREE_SELECTION: "SET_TREE_SELECTION",
    CHANGE_OBJECT_SELECTION: "CHANGE_OBJECT_SELECTION",
    CHANGE_NODE_SELECTION: "CHANGE_NODE_SELECTION",
    SET_ACTIVE_GROUP: "SET_ACTIVE_GROUP",
    SET_FOCUSED_SEQUENCE_INDEX: "SET_FOCUSED_SEQUENCE_INDEX",
    TOGGLE_GROUP_COLLAPSED: "TOGGLE_GROUP_COLLAPSED",
    TOGGLE_SELECTED_OBJECTS_LOCK: "TOGGLE_SELECTED_OBJECTS_LOCK",
    TOGGLE_SELECTED_OBJECTS_DISPLAY: "TOGGLE_SELECTED_OBJECTS_DISPLAY",
    DELETE_SELECTED_OBJECTS: "DELETE_SELECTED_OBJECTS",
    CHANGE_SELECTED_OBJECTS_GROUP: "CHANGE_SELECTED_OBJECTS_GROUP",
    SET_SINGLE_OBJECT_PROPERTIES: "SET_SINGLE_OBJECT_PROPERTIES",
    CHANGE_SELECTED_OBJECTS_BOUNDS: "CHANGE_SELECTED_OBJECTS_BOUNDS",
    RENAME_TREE_ITEM: "RENAME_TREE_ITEM",
    SET_GROUP_ADVANCE: "SET_GROUP_ADVANCE",
    UPDATE_NODE_PROPERTY: "UPDATE_NODE_PROPERTY",
    SET_PEN_PROPERTIES: "SET_PEN_PROPERTIES",
    SET_DRAW_TOOL_SETTINGS: "SET_DRAW_TOOL_SETTINGS",
    SET_GROUP_CHAR_CODE: "SET_GROUP_CHAR_CODE",
    SET_SEQUENCE_EDITOR_STATE: "SET_SEQUENCE_EDITOR_STATE",
    DELETE_GROUP_AND_UPDATE_SEQUENCE: "DELETE_GROUP_AND_UPDATE_SEQUENCE",
    COMMIT_SEQUENCE_HISTORY: "COMMIT_SEQUENCE_HISTORY",
    COMMIT_HISTORY: "COMMIT_HISTORY",
    UNDO: "UNDO",
    REDO: "REDO",
    EXPAND_STROKE: "EXPAND_STROKE",
    BOOLEAN_UNION: "BOOLEAN_UNION",
    UNLINK: "UNLINK",
    IMPORT_IMAGE: "IMPORT_IMAGE"
});

export function createEditorAction(type, payload = {}, meta = {}) {
    return {
        type,
        payload: payload && typeof payload === "object" ? payload : {},
        meta: meta && typeof meta === "object" ? meta : {},
        timestamp: Date.now()
    };
}
