/**
 * Unidirectional data flow convention (not a "scattered bus"):
 * 1. Write intent: CanvasDispatcher → REQUEST_* → CanvasController.dispatchAction → Command changes runtime
 * 2. Read state: EditorStore → STATE_CHANGED → UI (sole UI state outlet)
 * 3. Domain side effects: CurveManager emits DOMAIN_EVENTS → domain_event_bridge → EventBus → onDomainEffect
 * 4. Command history: EditorStore.commitCommand; undo/redo restoreFromHistoryMeta → snapshot patch → applyInteractionToRuntime
 * 5. Interaction SSOT: EditorStore (reduce → applyInteractionFromStore); CM is projection only, do not reverse-absorb
 */
export const CANVAS_EVENTS = Object.freeze({
    TREE_UPDATED: "tree-updated",
    SEQUENCE_CHANGED: "sequence-changed",
    SEQUENCE_ACTIVE_CHANGED: "sequence-active-changed",
    GLOBAL_SELECTION_UPDATED: "global-selection-updated",
    /** activeGroupId change only (no history write, no full property panel refresh) */
    ACTIVE_GROUP_CHANGED: "active-group-changed",
    FORCE_CANVAS_REDRAW: "force-canvas-redraw",
    MODEL_UPDATED: "model-state-updated",
    SYNC_TOOL_UI: "sync-tool-ui",
    LANGUAGE_CHANGED: "language-changed",
    THEME_PARAMS_UPDATED: "theme-params-updated",
    REQUEST_SET_TOOL_MODE: "request-set-tool-mode",
    REQUEST_SET_NODE_MODE: "request-set-node-mode",
    REQUEST_EDITOR_ACTION: "request-editor-action",
    REQUEST_COPY_SELECTED_OBJECTS: "request-copy-selected-objects",
    REQUEST_PASTE_COPIED_OBJECTS: "request-paste-copied-objects",
    REQUEST_DUPLICATE_SELECTED_OBJECTS: "request-duplicate-selected-objects",
    REQUEST_SET_TREE_SELECTION: "request-set-tree-selection",
    REQUEST_CHANGE_OBJECT_SELECTION: "request-change-object-selection",
    REQUEST_CHANGE_NODE_SELECTION: "request-change-node-selection",
    REQUEST_SET_ACTIVE_GROUP: "request-set-active-group",
    REQUEST_TOGGLE_GROUP_COLLAPSED: "request-toggle-group-collapsed",
    REQUEST_TOGGLE_SELECTED_OBJECTS_LOCK: "request-toggle-selected-objects-lock",
    REQUEST_TOGGLE_SELECTED_OBJECTS_DISPLAY: "request-toggle-selected-objects-display",
    REQUEST_DELETE_SELECTED_OBJECTS: "request-delete-selected-objects",
    REQUEST_CHANGE_SELECTED_OBJECTS_GROUP: "request-change-selected-objects-group",
    REQUEST_SET_SINGLE_OBJECT_PROPERTIES: "request-set-single-object-properties",
    REQUEST_CHANGE_SELECTED_OBJECTS_BOUNDS: "request-change-selected-objects-bounds",
    REQUEST_RENAME_TREE_ITEM: "request-rename-tree-item",
    REQUEST_SET_GROUP_ADVANCE: "request-set-group-advance",
    REQUEST_UPDATE_NODE_PROPERTY: "request-update-node-property",
    REQUEST_SET_PEN_PROPERTIES: "request-set-pen-properties",
    REQUEST_SET_ELLIPSE_PROPERTIES: "request-set-ellipse-properties",
    REQUEST_SET_FONT_SETTINGS: "request-set-font-settings",
    REQUEST_SET_GROUP_CHAR_CODE: "request-set-group-char-code",
    REQUEST_SET_SEQUENCE_EDITOR_STATE: "request-set-sequence-editor-state",
    REQUEST_DELETE_GROUP_AND_UPDATE_SEQUENCE: "request-delete-group-and-update-sequence",
    REQUEST_SEQUENCE_HISTORY_COMMIT: "request-sequence-history-commit",
    REQUEST_HISTORY_COMMIT: "request-history-commit",
    REQUEST_EXPAND_STROKE: "request-expand-stroke",
    REQUEST_BOOLEAN_UNION: "request-boolean-union",
    REQUEST_BOOLEAN_INTERSECTION: "request-boolean-intersection",
    REQUEST_BOOLEAN_DIFFERENCE: "request-boolean-difference",
    REQUEST_BOOLEAN_EXCLUSION: "request-boolean-exclusion",
    REQUEST_INSERT_NODE: "request-insert-node",
    REQUEST_DELETE_NODE: "request-delete-node",
    REQUEST_JOIN_NODE: "request-join-node",
    REQUEST_BREAK_NODE: "request-break-node",
    REQUEST_ADD_SEGMENT: "request-add-segment",
    REQUEST_DELETE_SEGMENT: "request-delete-segment",
    REQUEST_UNLINK: "request-unlink",
    REQUEST_IMPORT: "request-import",
    REQUEST_SAVE: "request-save",
    REQUEST_EXPORT: "request-export",
    REQUEST_LOAD: "request-load",
    REQUEST_NEW_PROJECT: "request-new-project",
    REQUEST_LOAD_FROM_CACHE: "request-load-from-cache",
    REQUEST_SAVE_TO_CACHE: "request-save-to-cache",
    REQUEST_UNDO: "request-undo",
    REQUEST_REDO: "request-redo",
    REQUEST_SAVE_VIEW_STATE: "request-save-view-state",
    REQUEST_FINISH_DRAWING_PATH: "request-finish-drawing-path",
    STATE_CHANGED: "canvas-state-changed"
});

export { EDITOR_ACTIONS as CANVAS_ACTIONS, createEditorAction as createCanvasAction } from "../domain/actions/editor_actions.js";
